#!/usr/bin/python3

def raise_exception():
    a = 2
    b = 'd'
    sum = a + b

    return sum
